name: Auto Update README

on:
  push:
    branches:
      - '**'  # Triggers on push to any branch

jobs:
  update-readme:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Commit and push if README changed
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        
        # Pull the latest changes
        git pull origin ${GITHUB_REF##*/} --rebase
        
        # Only commit if there are changes
        if git diff --quiet README.md; then
          echo "No changes to README"
        else
          git add README.md
          git commit -m "Auto-update README" || exit 0
          git push
        fi
